// <auto-generated />
using System;
using BackendEstadistica.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendEstadistica.Migrations
{
    [DbContext(typeof(ContextoBBDD))]
    [Migration("20240826085309_Estadisticas")]
    partial class Estadisticas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendEstadistica.Entidades.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trabajo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.HasIndex("PaisId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Conversion", b =>
                {
                    b.Property<int>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversionId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonedaOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ValorDestino")
                        .HasColumnType("float");

                    b.Property<double?>("ValorOrigen")
                        .HasColumnType("float");

                    b.HasKey("ConversionId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Conversion");
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaisId"));

                    b.Property<string>("Divisa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iso3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            PaisId = 1,
                            Divisa = "AFN",
                            Iso3 = "AFG",
                            Nombre = "Afganistán"
                        },
                        new
                        {
                            PaisId = 2,
                            Divisa = "ALL",
                            Iso3 = "ALB",
                            Nombre = "Albania"
                        },
                        new
                        {
                            PaisId = 3,
                            Divisa = "EUR",
                            Iso3 = "DEU",
                            Nombre = "Alemania"
                        },
                        new
                        {
                            PaisId = 4,
                            Divisa = "EUR",
                            Iso3 = "AND",
                            Nombre = "Andorra"
                        },
                        new
                        {
                            PaisId = 5,
                            Divisa = "AOA",
                            Iso3 = "AGO",
                            Nombre = "Angola"
                        },
                        new
                        {
                            PaisId = 6,
                            Divisa = "XCD",
                            Iso3 = "ATG",
                            Nombre = "Antigua y Barbuda"
                        },
                        new
                        {
                            PaisId = 7,
                            Divisa = "SAR",
                            Iso3 = "SAU",
                            Nombre = "Arabia Saudita"
                        },
                        new
                        {
                            PaisId = 8,
                            Divisa = "DZD",
                            Iso3 = "DZA",
                            Nombre = "Argelia"
                        },
                        new
                        {
                            PaisId = 9,
                            Divisa = "ARS",
                            Iso3 = "ARG",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            PaisId = 10,
                            Divisa = "AMD",
                            Iso3 = "ARM",
                            Nombre = "Armenia"
                        },
                        new
                        {
                            PaisId = 11,
                            Divisa = "AUD",
                            Iso3 = "AUS",
                            Nombre = "Australia"
                        },
                        new
                        {
                            PaisId = 12,
                            Divisa = "EUR",
                            Iso3 = "AUT",
                            Nombre = "Austria"
                        },
                        new
                        {
                            PaisId = 13,
                            Divisa = "AZN",
                            Iso3 = "AZE",
                            Nombre = "Azerbaiyán"
                        },
                        new
                        {
                            PaisId = 14,
                            Divisa = "BSD",
                            Iso3 = "BHS",
                            Nombre = "Bahamas"
                        },
                        new
                        {
                            PaisId = 15,
                            Divisa = "BHD",
                            Iso3 = "BHR",
                            Nombre = "Baréin"
                        },
                        new
                        {
                            PaisId = 16,
                            Divisa = "BDT",
                            Iso3 = "BGD",
                            Nombre = "Bangladés"
                        },
                        new
                        {
                            PaisId = 17,
                            Divisa = "BBD",
                            Iso3 = "BRB",
                            Nombre = "Barbados"
                        },
                        new
                        {
                            PaisId = 18,
                            Divisa = "BZD",
                            Iso3 = "BLZ",
                            Nombre = "Belice"
                        },
                        new
                        {
                            PaisId = 19,
                            Divisa = "XOF",
                            Iso3 = "BEN",
                            Nombre = "Benín"
                        },
                        new
                        {
                            PaisId = 20,
                            Divisa = "INR",
                            Iso3 = "BTN",
                            Nombre = "Bhután"
                        },
                        new
                        {
                            PaisId = 21,
                            Divisa = "BOB",
                            Iso3 = "BOL",
                            Nombre = "Bolivia"
                        },
                        new
                        {
                            PaisId = 22,
                            Divisa = "BAM",
                            Iso3 = "BIH",
                            Nombre = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            PaisId = 23,
                            Divisa = "BWP",
                            Iso3 = "BWA",
                            Nombre = "Botswana"
                        },
                        new
                        {
                            PaisId = 24,
                            Divisa = "BRL",
                            Iso3 = "BRA",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            PaisId = 25,
                            Divisa = "BND",
                            Iso3 = "BRN",
                            Nombre = "Brunéi"
                        },
                        new
                        {
                            PaisId = 26,
                            Divisa = "BGN",
                            Iso3 = "BGR",
                            Nombre = "Bulgaria"
                        },
                        new
                        {
                            PaisId = 27,
                            Divisa = "XOF",
                            Iso3 = "BFA",
                            Nombre = "Burkina Faso"
                        },
                        new
                        {
                            PaisId = 28,
                            Divisa = "BIF",
                            Iso3 = "BDI",
                            Nombre = "Burundi"
                        },
                        new
                        {
                            PaisId = 29,
                            Divisa = "INR",
                            Iso3 = "BTN",
                            Nombre = "Bután"
                        },
                        new
                        {
                            PaisId = 30,
                            Divisa = "CVE",
                            Iso3 = "CPV",
                            Nombre = "Cabo Verde"
                        },
                        new
                        {
                            PaisId = 31,
                            Divisa = "KHR",
                            Iso3 = "KHM",
                            Nombre = "Camboya"
                        },
                        new
                        {
                            PaisId = 32,
                            Divisa = "XAF",
                            Iso3 = "CMR",
                            Nombre = "Camerún"
                        },
                        new
                        {
                            PaisId = 33,
                            Divisa = "CAD",
                            Iso3 = "CAN",
                            Nombre = "Canadá"
                        },
                        new
                        {
                            PaisId = 34,
                            Divisa = "XAF",
                            Iso3 = "TCD",
                            Nombre = "Chad"
                        },
                        new
                        {
                            PaisId = 35,
                            Divisa = "CLP",
                            Iso3 = "CHL",
                            Nombre = "Chile"
                        },
                        new
                        {
                            PaisId = 36,
                            Divisa = "CNY",
                            Iso3 = "CHN",
                            Nombre = "China"
                        },
                        new
                        {
                            PaisId = 37,
                            Divisa = "COP",
                            Iso3 = "COL",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            PaisId = 38,
                            Divisa = "KMF",
                            Iso3 = "COM",
                            Nombre = "Comoras"
                        },
                        new
                        {
                            PaisId = 39,
                            Divisa = "XAF",
                            Iso3 = "COG",
                            Nombre = "Congo"
                        },
                        new
                        {
                            PaisId = 40,
                            Divisa = "CRC",
                            Iso3 = "CRI",
                            Nombre = "Costa Rica"
                        },
                        new
                        {
                            PaisId = 41,
                            Divisa = "HRK",
                            Iso3 = "HRV",
                            Nombre = "Croacia"
                        },
                        new
                        {
                            PaisId = 42,
                            Divisa = "CUP",
                            Iso3 = "CUB",
                            Nombre = "Cuba"
                        },
                        new
                        {
                            PaisId = 43,
                            Divisa = "EUR",
                            Iso3 = "CYP",
                            Nombre = "Chipre"
                        },
                        new
                        {
                            PaisId = 44,
                            Divisa = "DKK",
                            Iso3 = "DNK",
                            Nombre = "Dinamarca"
                        },
                        new
                        {
                            PaisId = 45,
                            Divisa = "XCD",
                            Iso3 = "DMA",
                            Nombre = "Dominica"
                        },
                        new
                        {
                            PaisId = 46,
                            Divisa = "EGP",
                            Iso3 = "EGY",
                            Nombre = "Egipto"
                        },
                        new
                        {
                            PaisId = 47,
                            Divisa = "USD",
                            Iso3 = "SLV",
                            Nombre = "El Salvador"
                        },
                        new
                        {
                            PaisId = 48,
                            Divisa = "AED",
                            Iso3 = "ARE",
                            Nombre = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            PaisId = 49,
                            Divisa = "USD",
                            Iso3 = "ECU",
                            Nombre = "Ecuador"
                        },
                        new
                        {
                            PaisId = 50,
                            Divisa = "ERN",
                            Iso3 = "ERI",
                            Nombre = "Eritrea"
                        },
                        new
                        {
                            PaisId = 51,
                            Divisa = "EUR",
                            Iso3 = "SVK",
                            Nombre = "Eslovaquia"
                        },
                        new
                        {
                            PaisId = 52,
                            Divisa = "EUR",
                            Iso3 = "SVN",
                            Nombre = "Eslovenia"
                        },
                        new
                        {
                            PaisId = 53,
                            Divisa = "EUR",
                            Iso3 = "ESP",
                            Nombre = "España"
                        },
                        new
                        {
                            PaisId = 54,
                            Divisa = "USD",
                            Iso3 = "USA",
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            PaisId = 55,
                            Divisa = "EUR",
                            Iso3 = "EST",
                            Nombre = "Estonia"
                        },
                        new
                        {
                            PaisId = 56,
                            Divisa = "ETB",
                            Iso3 = "ETH",
                            Nombre = "Etiopía"
                        },
                        new
                        {
                            PaisId = 57,
                            Divisa = "FJD",
                            Iso3 = "FJI",
                            Nombre = "Fiji"
                        },
                        new
                        {
                            PaisId = 58,
                            Divisa = "PHP",
                            Iso3 = "PHL",
                            Nombre = "Filipinas"
                        },
                        new
                        {
                            PaisId = 59,
                            Divisa = "EUR",
                            Iso3 = "FIN",
                            Nombre = "Finlandia"
                        },
                        new
                        {
                            PaisId = 60,
                            Divisa = "EUR",
                            Iso3 = "FRA",
                            Nombre = "Francia"
                        },
                        new
                        {
                            PaisId = 61,
                            Divisa = "XAF",
                            Iso3 = "GAB",
                            Nombre = "Gabón"
                        },
                        new
                        {
                            PaisId = 62,
                            Divisa = "GMD",
                            Iso3 = "GMB",
                            Nombre = "Gambia"
                        },
                        new
                        {
                            PaisId = 63,
                            Divisa = "GEL",
                            Iso3 = "GEO",
                            Nombre = "Georgia"
                        },
                        new
                        {
                            PaisId = 64,
                            Divisa = "GHS",
                            Iso3 = "GHA",
                            Nombre = "Ghana"
                        },
                        new
                        {
                            PaisId = 65,
                            Divisa = "XCD",
                            Iso3 = "GRD",
                            Nombre = "Granada"
                        },
                        new
                        {
                            PaisId = 66,
                            Divisa = "EUR",
                            Iso3 = "GRC",
                            Nombre = "Grecia"
                        },
                        new
                        {
                            PaisId = 67,
                            Divisa = "GTQ",
                            Iso3 = "GTM",
                            Nombre = "Guatemala"
                        },
                        new
                        {
                            PaisId = 68,
                            Divisa = "GNF",
                            Iso3 = "GIN",
                            Nombre = "Guinea"
                        },
                        new
                        {
                            PaisId = 69,
                            Divisa = "XOF",
                            Iso3 = "GNB",
                            Nombre = "Guinea-Bisáu"
                        },
                        new
                        {
                            PaisId = 70,
                            Divisa = "GYD",
                            Iso3 = "GUY",
                            Nombre = "Guyana"
                        },
                        new
                        {
                            PaisId = 71,
                            Divisa = "HTG",
                            Iso3 = "HTI",
                            Nombre = "Haití"
                        },
                        new
                        {
                            PaisId = 72,
                            Divisa = "HNL",
                            Iso3 = "HND",
                            Nombre = "Honduras"
                        },
                        new
                        {
                            PaisId = 73,
                            Divisa = "HUF",
                            Iso3 = "HUN",
                            Nombre = "Hungría"
                        },
                        new
                        {
                            PaisId = 74,
                            Divisa = "INR",
                            Iso3 = "IND",
                            Nombre = "India"
                        },
                        new
                        {
                            PaisId = 75,
                            Divisa = "IDR",
                            Iso3 = "IDN",
                            Nombre = "Indonesia"
                        },
                        new
                        {
                            PaisId = 76,
                            Divisa = "IQD",
                            Iso3 = "IRQ",
                            Nombre = "Irak"
                        },
                        new
                        {
                            PaisId = 77,
                            Divisa = "IRR",
                            Iso3 = "IRN",
                            Nombre = "Irán"
                        },
                        new
                        {
                            PaisId = 78,
                            Divisa = "EUR",
                            Iso3 = "IRL",
                            Nombre = "Irlanda"
                        },
                        new
                        {
                            PaisId = 79,
                            Divisa = "ISK",
                            Iso3 = "ISL",
                            Nombre = "Islandia"
                        },
                        new
                        {
                            PaisId = 80,
                            Divisa = "USD",
                            Iso3 = "MHL",
                            Nombre = "Islas Marshall"
                        },
                        new
                        {
                            PaisId = 81,
                            Divisa = "SBD",
                            Iso3 = "SLB",
                            Nombre = "Islas Salomón"
                        },
                        new
                        {
                            PaisId = 82,
                            Divisa = "USD",
                            Iso3 = "VGB",
                            Nombre = "Islas Vírgenes Británicas"
                        },
                        new
                        {
                            PaisId = 83,
                            Divisa = "USD",
                            Iso3 = "VIR",
                            Nombre = "Islas Vírgenes de los Estados Unidos"
                        },
                        new
                        {
                            PaisId = 84,
                            Divisa = "EUR",
                            Iso3 = "ITA",
                            Nombre = "Italia"
                        },
                        new
                        {
                            PaisId = 85,
                            Divisa = "JMD",
                            Iso3 = "JAM",
                            Nombre = "Jamaica"
                        },
                        new
                        {
                            PaisId = 86,
                            Divisa = "JPY",
                            Iso3 = "JPN",
                            Nombre = "Japón"
                        },
                        new
                        {
                            PaisId = 87,
                            Divisa = "JOD",
                            Iso3 = "JOR",
                            Nombre = "Jordania"
                        },
                        new
                        {
                            PaisId = 88,
                            Divisa = "KZT",
                            Iso3 = "KAZ",
                            Nombre = "Kazajistán"
                        },
                        new
                        {
                            PaisId = 89,
                            Divisa = "KES",
                            Iso3 = "KEN",
                            Nombre = "Kenia"
                        },
                        new
                        {
                            PaisId = 90,
                            Divisa = "KGS",
                            Iso3 = "KGZ",
                            Nombre = "Kirguistán"
                        },
                        new
                        {
                            PaisId = 91,
                            Divisa = "AUD",
                            Iso3 = "KIR",
                            Nombre = "Kiribati"
                        },
                        new
                        {
                            PaisId = 92,
                            Divisa = "KWD",
                            Iso3 = "KWT",
                            Nombre = "Kuwait"
                        },
                        new
                        {
                            PaisId = 93,
                            Divisa = "LAK",
                            Iso3 = "LAO",
                            Nombre = "Laos"
                        },
                        new
                        {
                            PaisId = 94,
                            Divisa = "EUR",
                            Iso3 = "LVA",
                            Nombre = "Latvia"
                        },
                        new
                        {
                            PaisId = 95,
                            Divisa = "LBP",
                            Iso3 = "LBN",
                            Nombre = "Líbano"
                        },
                        new
                        {
                            PaisId = 96,
                            Divisa = "LRD",
                            Iso3 = "LBR",
                            Nombre = "Liberia"
                        },
                        new
                        {
                            PaisId = 97,
                            Divisa = "LYD",
                            Iso3 = "LBY",
                            Nombre = "Libia"
                        },
                        new
                        {
                            PaisId = 98,
                            Divisa = "CHF",
                            Iso3 = "LIE",
                            Nombre = "Liechtenstein"
                        },
                        new
                        {
                            PaisId = 99,
                            Divisa = "EUR",
                            Iso3 = "LTU",
                            Nombre = "Lituania"
                        },
                        new
                        {
                            PaisId = 100,
                            Divisa = "EUR",
                            Iso3 = "LUX",
                            Nombre = "Luxemburgo"
                        },
                        new
                        {
                            PaisId = 101,
                            Divisa = "MGA",
                            Iso3 = "MDG",
                            Nombre = "Madagascar"
                        },
                        new
                        {
                            PaisId = 102,
                            Divisa = "MYR",
                            Iso3 = "MYS",
                            Nombre = "Malasia"
                        },
                        new
                        {
                            PaisId = 103,
                            Divisa = "MWK",
                            Iso3 = "MWI",
                            Nombre = "Malawi"
                        },
                        new
                        {
                            PaisId = 104,
                            Divisa = "MVR",
                            Iso3 = "MDV",
                            Nombre = "Maldivas"
                        },
                        new
                        {
                            PaisId = 105,
                            Divisa = "XOF",
                            Iso3 = "MLI",
                            Nombre = "Malí"
                        },
                        new
                        {
                            PaisId = 106,
                            Divisa = "EUR",
                            Iso3 = "MLT",
                            Nombre = "Malta"
                        },
                        new
                        {
                            PaisId = 107,
                            Divisa = "MAD",
                            Iso3 = "MAR",
                            Nombre = "Marruecos"
                        },
                        new
                        {
                            PaisId = 108,
                            Divisa = "MUR",
                            Iso3 = "MUS",
                            Nombre = "Mauricio"
                        },
                        new
                        {
                            PaisId = 109,
                            Divisa = "MRU",
                            Iso3 = "MRT",
                            Nombre = "Mauritania"
                        },
                        new
                        {
                            PaisId = 110,
                            Divisa = "MXN",
                            Iso3 = "MEX",
                            Nombre = "México"
                        },
                        new
                        {
                            PaisId = 111,
                            Divisa = "USD",
                            Iso3 = "FSM",
                            Nombre = "Micronesia"
                        },
                        new
                        {
                            PaisId = 112,
                            Divisa = "MDL",
                            Iso3 = "MDA",
                            Nombre = "Moldavia"
                        },
                        new
                        {
                            PaisId = 113,
                            Divisa = "EUR",
                            Iso3 = "MCO",
                            Nombre = "Mónaco"
                        },
                        new
                        {
                            PaisId = 114,
                            Divisa = "MNT",
                            Iso3 = "MNG",
                            Nombre = "Mongolia"
                        },
                        new
                        {
                            PaisId = 115,
                            Divisa = "EUR",
                            Iso3 = "MNE",
                            Nombre = "Montenegro"
                        },
                        new
                        {
                            PaisId = 116,
                            Divisa = "CZK",
                            Iso3 = "CZE",
                            Nombre = "Moravia"
                        },
                        new
                        {
                            PaisId = 117,
                            Divisa = "MZN",
                            Iso3 = "MOZ",
                            Nombre = "Mozambique"
                        },
                        new
                        {
                            PaisId = 118,
                            Divisa = "NAD",
                            Iso3 = "NAM",
                            Nombre = "Namibia"
                        },
                        new
                        {
                            PaisId = 119,
                            Divisa = "AUD",
                            Iso3 = "NRU",
                            Nombre = "Nauru"
                        },
                        new
                        {
                            PaisId = 120,
                            Divisa = "NPR",
                            Iso3 = "NPL",
                            Nombre = "Nepal"
                        },
                        new
                        {
                            PaisId = 121,
                            Divisa = "NIO",
                            Iso3 = "NIC",
                            Nombre = "Nicaragua"
                        },
                        new
                        {
                            PaisId = 122,
                            Divisa = "XOF",
                            Iso3 = "NER",
                            Nombre = "Níger"
                        },
                        new
                        {
                            PaisId = 123,
                            Divisa = "NGN",
                            Iso3 = "NGA",
                            Nombre = "Nigeria"
                        },
                        new
                        {
                            PaisId = 124,
                            Divisa = "NOK",
                            Iso3 = "NOR",
                            Nombre = "Noruega"
                        },
                        new
                        {
                            PaisId = 125,
                            Divisa = "NZD",
                            Iso3 = "NZL",
                            Nombre = "Nueva Zelanda"
                        },
                        new
                        {
                            PaisId = 126,
                            Divisa = "OMR",
                            Iso3 = "OMN",
                            Nombre = "Omán"
                        },
                        new
                        {
                            PaisId = 127,
                            Divisa = "EUR",
                            Iso3 = "NLD",
                            Nombre = "Países Bajos"
                        },
                        new
                        {
                            PaisId = 128,
                            Divisa = "PKR",
                            Iso3 = "PAK",
                            Nombre = "Pakistán"
                        },
                        new
                        {
                            PaisId = 129,
                            Divisa = "USD",
                            Iso3 = "PLW",
                            Nombre = "Palau"
                        },
                        new
                        {
                            PaisId = 130,
                            Divisa = "PAB",
                            Iso3 = "PAN",
                            Nombre = "Panamá"
                        },
                        new
                        {
                            PaisId = 131,
                            Divisa = "PGK",
                            Iso3 = "PNG",
                            Nombre = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            PaisId = 132,
                            Divisa = "PYG",
                            Iso3 = "PRY",
                            Nombre = "Paraguay"
                        },
                        new
                        {
                            PaisId = 133,
                            Divisa = "PEN",
                            Iso3 = "PER",
                            Nombre = "Perú"
                        },
                        new
                        {
                            PaisId = 134,
                            Divisa = "PLN",
                            Iso3 = "POL",
                            Nombre = "Polonia"
                        },
                        new
                        {
                            PaisId = 135,
                            Divisa = "EUR",
                            Iso3 = "PRT",
                            Nombre = "Portugal"
                        },
                        new
                        {
                            PaisId = 136,
                            Divisa = "QAR",
                            Iso3 = "QAT",
                            Nombre = "Qatar"
                        },
                        new
                        {
                            PaisId = 137,
                            Divisa = "RON",
                            Iso3 = "ROU",
                            Nombre = "Rumanía"
                        },
                        new
                        {
                            PaisId = 138,
                            Divisa = "RUB",
                            Iso3 = "RUS",
                            Nombre = "Rusia"
                        },
                        new
                        {
                            PaisId = 139,
                            Divisa = "RWF",
                            Iso3 = "RWA",
                            Nombre = "Rwanda"
                        },
                        new
                        {
                            PaisId = 140,
                            Divisa = "XCD",
                            Iso3 = "KNA",
                            Nombre = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            PaisId = 141,
                            Divisa = "EUR",
                            Iso3 = "SMR",
                            Nombre = "San Marino"
                        },
                        new
                        {
                            PaisId = 142,
                            Divisa = "STN",
                            Iso3 = "STP",
                            Nombre = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            PaisId = 143,
                            Divisa = "XOF",
                            Iso3 = "SEN",
                            Nombre = "Senegal"
                        },
                        new
                        {
                            PaisId = 144,
                            Divisa = "RSD",
                            Iso3 = "SRB",
                            Nombre = "Serbia"
                        },
                        new
                        {
                            PaisId = 145,
                            Divisa = "SCR",
                            Iso3 = "SYC",
                            Nombre = "Seychelles"
                        },
                        new
                        {
                            PaisId = 146,
                            Divisa = "SLL",
                            Iso3 = "SLE",
                            Nombre = "Sierra Leona"
                        },
                        new
                        {
                            PaisId = 147,
                            Divisa = "SGD",
                            Iso3 = "SGP",
                            Nombre = "Singapur"
                        },
                        new
                        {
                            PaisId = 148,
                            Divisa = "SYP",
                            Iso3 = "SYR",
                            Nombre = "Siria"
                        },
                        new
                        {
                            PaisId = 149,
                            Divisa = "SOS",
                            Iso3 = "SOM",
                            Nombre = "Somalia"
                        },
                        new
                        {
                            PaisId = 150,
                            Divisa = "LKR",
                            Iso3 = "LKA",
                            Nombre = "Sri Lanka"
                        },
                        new
                        {
                            PaisId = 151,
                            Divisa = "SDG",
                            Iso3 = "SDN",
                            Nombre = "Sudán"
                        },
                        new
                        {
                            PaisId = 152,
                            Divisa = "SSP",
                            Iso3 = "SSD",
                            Nombre = "Sudán del Sur"
                        },
                        new
                        {
                            PaisId = 153,
                            Divisa = "SEK",
                            Iso3 = "SWE",
                            Nombre = "Suecia"
                        },
                        new
                        {
                            PaisId = 154,
                            Divisa = "CHF",
                            Iso3 = "CHE",
                            Nombre = "Suiza"
                        },
                        new
                        {
                            PaisId = 155,
                            Divisa = "STN",
                            Iso3 = "STP",
                            Nombre = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            PaisId = 156,
                            Divisa = "THB",
                            Iso3 = "THA",
                            Nombre = "Tailandia"
                        },
                        new
                        {
                            PaisId = 157,
                            Divisa = "TWD",
                            Iso3 = "TWN",
                            Nombre = "Taiwán"
                        },
                        new
                        {
                            PaisId = 158,
                            Divisa = "TZS",
                            Iso3 = "TZA",
                            Nombre = "Tanzania"
                        },
                        new
                        {
                            PaisId = 159,
                            Divisa = "XOF",
                            Iso3 = "TGO",
                            Nombre = "Togo"
                        },
                        new
                        {
                            PaisId = 160,
                            Divisa = "TOP",
                            Iso3 = "TON",
                            Nombre = "Tonga"
                        },
                        new
                        {
                            PaisId = 161,
                            Divisa = "TTD",
                            Iso3 = "TTO",
                            Nombre = "Trinidad y Tobago"
                        },
                        new
                        {
                            PaisId = 162,
                            Divisa = "TND",
                            Iso3 = "TUN",
                            Nombre = "Túnez"
                        },
                        new
                        {
                            PaisId = 163,
                            Divisa = "TMT",
                            Iso3 = "TKM",
                            Nombre = "Turkmenistán"
                        },
                        new
                        {
                            PaisId = 164,
                            Divisa = "TRY",
                            Iso3 = "TUR",
                            Nombre = "Turquía"
                        },
                        new
                        {
                            PaisId = 165,
                            Divisa = "AUD",
                            Iso3 = "TUV",
                            Nombre = "Tuvalu"
                        },
                        new
                        {
                            PaisId = 166,
                            Divisa = "UAH",
                            Iso3 = "UKR",
                            Nombre = "Ucrania"
                        },
                        new
                        {
                            PaisId = 167,
                            Divisa = "UGX",
                            Iso3 = "UGA",
                            Nombre = "Uganda"
                        },
                        new
                        {
                            PaisId = 168,
                            Divisa = "UYU",
                            Iso3 = "URY",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            PaisId = 169,
                            Divisa = "UZS",
                            Iso3 = "UZB",
                            Nombre = "Uzbekistán"
                        },
                        new
                        {
                            PaisId = 170,
                            Divisa = "VUV",
                            Iso3 = "VUT",
                            Nombre = "Vanuatu"
                        },
                        new
                        {
                            PaisId = 171,
                            Divisa = "VES",
                            Iso3 = "VEN",
                            Nombre = "Venezuela"
                        },
                        new
                        {
                            PaisId = 172,
                            Divisa = "VND",
                            Iso3 = "VNM",
                            Nombre = "Vietnam"
                        },
                        new
                        {
                            PaisId = 173,
                            Divisa = "YER",
                            Iso3 = "YEM",
                            Nombre = "Yemen"
                        },
                        new
                        {
                            PaisId = 174,
                            Divisa = "ZMW",
                            Iso3 = "ZMB",
                            Nombre = "Zambia"
                        },
                        new
                        {
                            PaisId = 175,
                            Divisa = "ZWL",
                            Iso3 = "ZWE",
                            Nombre = "Zimbabue"
                        });
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<int>("ClienteDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteOrigenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ImporteEnviado")
                        .HasColumnType("float");

                    b.Property<double?>("ImporteRecibido")
                        .HasColumnType("float");

                    b.Property<bool?>("IsOutlier")
                        .HasColumnType("bit");

                    b.HasKey("TransaccionId");

                    b.HasIndex("ClienteDestinoId");

                    b.HasIndex("ClienteOrigenId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BackendEstadistica.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Cliente", b =>
                {
                    b.HasOne("BackendEstadistica.Entidades.Pais", "Pais")
                        .WithMany("Clientes")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Conversion", b =>
                {
                    b.HasOne("BackendEstadistica.Entidades.Cliente", "Cliente")
                        .WithMany("Conversiones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Transaccion", b =>
                {
                    b.HasOne("BackendEstadistica.Entidades.Cliente", "ClienteDestino")
                        .WithMany("TransaccionesDestino")
                        .HasForeignKey("ClienteDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendEstadistica.Entidades.Cliente", "ClienteOrigen")
                        .WithMany("TransaccionesOrigen")
                        .HasForeignKey("ClienteOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteDestino");

                    b.Navigation("ClienteOrigen");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackendEstadistica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackendEstadistica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendEstadistica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackendEstadistica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Cliente", b =>
                {
                    b.Navigation("Conversiones");

                    b.Navigation("TransaccionesDestino");

                    b.Navigation("TransaccionesOrigen");
                });

            modelBuilder.Entity("BackendEstadistica.Entidades.Pais", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
