global using Microsoft.AspNetCore.Mvc;
global using TuProyecto.Biblioteca;
global using Microsoft.AspNetCore.Http;
global using BackendEstadistica.Models;
global using BackendEstadistica.Repositorios;
global using BackendEstadistica.Servicios;
global using System.ComponentModel.DataAnnotations;
global using BackendEstadistica.Entidades;
global using ApiBasesDeDatosProyecto.Perfiles;