# YAML modificado para corregir las rutas en Windows.
name: Build, Test, and Deploy ASP.Net Core app to Azure Web App - ChachiBackend

on:
  push:
    branches:
      - produccion
  workflow_dispatch:

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Build with dotnet
      run: dotnet build backend-estadistica/src/BackendEstadistica/BackendEstadistica.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish backend-estadistica/src/BackendEstadistica/BackendEstadistica.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: |
          backend-estadistica/src/BackendEstadistica/BackendEstadistica.sln
          backend-estadistica/src/BackendEstadistica/TestEstadistica
          ${{env.DOTNET_ROOT}}/myapp

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore backend-estadistica\src\BackendEstadistica.sln
        shell: cmd

      - name: Build Solution
        run: msbuild backend-estadistica\src\BackendEstadistica.sln /p:Configuration=Release
        shell: cmd

      - name: Run Tests
        run: vstest.console.exe backend-estadistica\TestEstadistica\bin\Release\net8.0\TestEstadistica.dll --parallel
        shell: cmd

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ChachiBackend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1C79C43975924D0A9D9A5CD7855B4F7A }}
